spring:
  application:
    name: transaction-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  config:
    import: optional:configserver:http://config-server:8888

  cloud:
    config:
      uri: ${SPRING_CLOUD_CONFIG_URI:http://config-server:8888}
      fail-fast: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://eureka-server:8761/eureka}
    register-with-eureka: true
    fetch-registry: true

transaction:
  free-limit: ${TRANSACTION_FREE_LIMIT:500.00}

server:
  port: 8181